### ISSUE TITLE
Still unable to bring up certain categories in Movies

### ISSUE THREAD

**Issue by Beckles83** [mrknow/filmkodi#112] opened 2016-02-18 12:22 UTC
Hi Mrknow,

I saw in one of your previous posts that you said to wait a few hours and then install the new version of Specto. Forgive me as I am a novice at this. I have a digixstream box and the app for Specto was already installed on it. Could you explain to me how to install the new version so that it will work properly again? I think it has been updating itself regularly but just on the off chance it does not, I would really like to make this app functional. It has been a joy to use!

**Comment by mrknow** [comment] 2016-02-18 17:51
You can send an error logs ? Here you have instructions http://kodi.wiki/view/Log_file/Easy

**Comment by Beckles83** [comment] 2016-02-19 11:48
I will try to do this when I get a chance to sit down and mess with it. Didn't want you to think I forgot

**Comment by mrknow** [comment] 2016-02-20 19:42
Closed as duplicate of #109

**Closed by mrknow** 2016-02-20 19:42 UTC
