### ISSUE TITLE
Specto updated incompatible

### ISSUE THREAD

**Issue by Delwashy** [mrknow/filmkodi#100] opened 2016-02-15 02:52 UTC
have Specto version 2016.02.06.1 running on my Android box using Helix 14.2 iv'e just got an update for specto version 2016.02.15.1 it will not update as it is saying Add-on is incompatibleor has been marked broken in repository dependencies not met.Please contact Add-on author. My Specto is still working but i will not be able to update it any feed back or advice would be greatly appreciated is there a new plugin i can use or is there a problem as it seems i've missed an update as on my other device it's version 2016.02.07.3 any help please

**Comment by karnage11** [comment] 2016-02-15 02:55
the new update is updating for me right now to 2016.02.15.1

**Comment by karnage11** [comment] 2016-02-15 02:55
its at 31% atm

**Comment by karnage11** [comment] 2016-02-15 02:56
https://github.com/mrknow/filmkodi/issues/81 it has update 2016.02.07.3 here at the bottom

**Comment by Delwashy** [comment] 2016-02-15 03:13
ive managed to get it to update to version 2016.02.07.3 but it's still saying update available in repository version 2016.02.15.1 what i might do is just uninstall the repository as it's saying it's not incompatible? but my version 2016.02.07.3 is working fine. Can someone confirm which isw the latest version of Specto please

**Comment by karnage11** [comment] 2016-02-15 03:13
the lastest update is 206.02.15.1 it updated for me

**Comment by karnage11** [comment] 2016-02-15 03:14
might take awhile to update to see a % , but it worked for me

**Comment by Delwashy** [comment] 2016-02-15 03:28
the latest update 2016.02.15.1 which is not compatible with Helix 14.2 on my M8 Android box i may have to update my kodi what a bummer as it's updated fine on  kodi 15.2 so anything less then 15.2 it anit compatible

**Comment by karnage11** [comment] 2016-02-15 03:28
I am on Kodi 16 Jarvis

**Comment by Delwashy** [comment] 2016-02-15 03:32
it makes sense cheers pal

**Comment by karnage11** [comment] 2016-02-15 03:32
hope you get it working , good luck

**Comment by Delwashy** [comment] 2016-02-15 03:37
Like i said it's working fine on version 2016.02.07.3 at the moment but at some stage i will have to updte kodi on my  Android box but it's so stable and i don't fancy doing a new bulid as i've got just as i like it

**Comment by paulinthesun** [comment] 2016-02-15 05:13
Hi looks like I am having same problem I have an old box MX and I can not update to the new version I am on 14.2 my box will not update past 14.2, all other add-ons are working ok, is this the end for me now or will the next update fix this error

**Comment by Terrahawk** [comment] 2016-02-15 13:23
Last nights update not working. Isengard 15.2 silly Fork-ing thing!

**Comment by karnage11** [comment] 2016-02-15 17:54
it updated for me fine

**Comment by Jadvena** [comment] 2016-02-15 21:22
Not getting anything from repo shows 2016.02.15 as an option bit days failed to install a dependency.. ziddo z6 pro I'll try on my Amazon and let you know

**Comment by Jadvena** [comment] 2016-02-15 22:03
Amason fire tv updated everything no issues same exact build a ziddo x6 pro no idea.. I did notice on the ziddo axel thing didn't update either maybe the cause but other addons updated

**Comment by Jadvena** [comment] 2016-02-15 22:14
Exact error says date utility arrow failed to install trakt.pyramid failed to install failed to install a dependency if it helps anyone

**Comment by mrknow** [comment] 2016-02-18 00:14
in a few hours try install new version 2015.02.17

**Comment by karnage11** [comment] 2016-02-18 00:15
awesome , does the tv shows work with updating episodes

**Comment by waemun** [comment] 2016-02-18 00:42
perfect, i was wondering if the update was ready or not. it seems we are seeing it inside the media center as avail, but it isnt up yet, is that correct?

**Comment by mrknow** [comment] 2016-02-20 20:03
Fixed in new version 2016.02.20.2

**Closed by mrknow** 2016-02-20 20:03 UTC

**Comment by karnage11** [comment] 2016-02-20 20:06
Thanks MrKnow

**Comment by Delwashy** [comment] 2016-02-20 20:43
Thank you MrKnow just a quick question is it compatible with frodo 12.2 or am i asking for a miracle

**Comment by ateliernm** [comment] 2016-09-04 17:50
I'm using v13.2 gotham on android media box and first EXODUS has never worked always shown as "incompatible" and now SPECTO is also not working and showing as incompatible, same thing is happening with SALT. Just can't find any way to fix it, so...HELP! anyone, please.

**Comment by Jadvena** [comment] 2016-09-05 15:33
Update kodi itself to 16.1 all fixed


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone
-------- Original message --------From: ateliernm <notifications@github.com> Date: 9/4/16  1:50 PM  (GMT-05:00) To: mrknow/filmkodi <filmkodi@noreply.github.com> Cc: Jadvena <jadvena@aol.com>, Comment <comment@noreply.github.com> Subject: Re: [mrknow/filmkodi] Specto updated incompatible (#100) 
I'm using v13.2 gotham on android media box and first EXODUS has never worked always shown as "incompatible" and now SPECTO is also not working and showing as incompatible, same thing is happening with SALT. Just can't find any way to fix it, so...HELP! anyone, please.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mrknow/filmkodi","title":"mrknow/filmkodi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mrknow/filmkodi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ateliernm in #100: I'm using v13.2 gotham on android media box and first EXODUS has never worked always shown as \"incompatible\" and now SPECTO is also not working and showing as incompatible, same thing is happening with SALT. Just can't find any way to fix it, so...HELP! anyone, please."}],"action":{"name":"View Issue","url":"https://github.com/mrknow/filmkodi/issues/100#issuecomment-244618235"}}}
